# Basic
title: çŒªå’ªèµ›_Official
subtitle: åšå®¢1.0
description: å…³æ³¨äº®äº®å–µï¼Œå…³æ³¨äº®äº®è°¢è°¢å–µ~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: çŒªå’ªç‹æ¥è¾½
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: å“¼å”§~
url: "https://zhumisai.github.io"

# åšå®¢æ˜¯å¦è‡ªåŠ¨ç”Ÿæˆç›®å½•ï¼Œfalseä¸ºä¸ç”Ÿæˆ
enableToc: true

# Comment
comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
#    disqus: leopard
    # uyan: 2143225  # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    # weibo: =
    github: zhumisai
    # zhihu:
    # juejin: xxx
    # jianshu:
    # twitter: 
    mail: fake_email@github.com


# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
# baidu:
    # id: aaaaaaaaaaa

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
#ga:
#    id: UA-84134159-3
#    host: auto


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


exclude: [
  # å¿½ç•¥æ–‡ä»¶å¤¹ï¼Œå­˜åœ¨æœ¬åœ°(utf-8)æ— æ³•è§£æçš„å­—ç¬¦
    # downloads
]